drop table if exists item CASCADE;
create table item
(
    id        bigint generated by default as identity,
    perfume_name varchar(10),
    brand       varchar(10),
    topNote     varchar(20),
    middleNote  varchar(20),
    baseNote    varchar(20)
    primary key (id)
);